import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Providers/ThemeProvider";
import ReduxProvider from "@/Providers/ReduxProvider";
import ToastProvider from "@/Providers/ToastProvider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Toaster  toastOptions={{
            classNames:{
              toast:"bg-black dark:bg-white border-none ",
              title:"text-base dark:text-black text-white",
              icon:"text-white dark:text-black",
              closeButton:"text-white dark:text-black"
            }
          }}  position="bottom-right"  className="text-2xl"  />
        </div>
        <ThemeProvider attribute="class" defaultTheme="system">
          {/* <ToastProvider />
           */}
          <ReduxProvider>{children}</ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
